services:
    maria-db:
        image: mariadb:10.6
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
          - ./data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
  db_data: