services:
    client-ui:
        container_name: client-ui
        build:
            context: ./client-ui
            dockerfile: Dockerfile
        ports:
            - "4200:80"
        depends_on:
            -   backend
            -  keycloak

    backend:
        image: backend
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SPRING_DATASOURCE_URL: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
            SPRING_DATASOURCE_USERNAME: ${DB_USER}
            SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
            server.port: 8081
            server.address: 0.0.0.0
        depends_on:
            - maria-db

    maria-db:
        image: mariadb:10.6
        container_name: maria-db
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        volumes:
          - ./data/mariadb:/var/lib/mysql
        ports:
            - "${DB_PORT}:${DB_PORT}"

    postgres-keycloak:
        image: postgres:16
        container_name: postgres-keycloak
        environment:
            POSTGRES_DB: ${KEYCLOAK_DB_DATABASE}
            POSTGRES_USER: ${KEYCLOAK_DB_USER}
            POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
        restart: unless-stopped
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "${KEYCLOAK_DB_PORT}:${KEYCLOAK_DB_PORT}"

    keycloak:
        container_name: keycloak-openid-provider
        image: quay.io/keycloak/keycloak:25.0.5
        command: [ "start-dev"]
        ports:
            - "8083:8083"
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/${KEYCLOAK_DB_DATABASE}
            KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
            KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
            KC_HTTP_PORT: 8083
            KC_HOSTNAME: localhost
            KC_HTTP_RELATIVE_PATH: /
            KC_HTTP_ENABLED: true
            KC_HEALTH_ENABLED: true
            KC_METRICS_ENABLED: true
        depends_on:
            -   postgres-keycloak
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8083/health/ready" ]
            interval: 15s
            timeout: 2s
            retries: 15

